query Item($id: UUID!) {
  itemById(id: $id) {
    id
    label
    public
    value
    itemByParentId {
      id
      label
    }
    permissionsByItemId {
      nodes {
        usersAndGroupByUserOrGroupId {
          id
          name
        }
      }
    }
  }
}
