query Item($id: UUID!) {
  itemById(id: $id) {
    id
    label
    public
    value
    itemRelationshipsByChildId {
      nodes {
        itemByParentId {
          id,
          label
        }
      }
    }
    permissionsByItemId {
      nodes {
        id
        role
        usersAndGroupByUserOrGroupId {
          id
          name
        }
      }
    }
  }
}
