query RecentItems {
  allItems(
    orderBy: TIME_UPDATED_DESC,
    first: 30
  ) {
    nodes {
      id
      label
      value
      timeCreated
      timeUpdated
      userIsWriter @client
      permissionsByItemId {
        nodes {
          id
          itemId
          role
          timeCreated
          usersAndGroupByUserOrGroupId {
            id
            name
          }
        }
      }
    }
  }
}
