query ItemChildren($condition: ItemRelationshipCondition!) {
  allItemRelationships(condition: $condition, orderBy: TIME_CREATED_ASC) {
    nodes {
      id
      itemByChildId {
        id
        label
        value
        timeCreated
        timeUpdated
        userIsWriter @client
        permissionsByItemId {
          nodes {
            id
            itemId
            role
            timeCreated
            usersAndGroupByUserOrGroupId {
              id
              name
            }
          }
        }
      }
    }
  }
}
